name: Deploy Playground

on:
  push:
    branches: [main]

jobs:
  deploy-playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g --force corepack && corepack enable

      - name: Set node version to 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.5'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile && node scripts/bootstrap.mjs

      - name: Build playground
        run: pnpm build:play

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-page
          folder: packages/varlet-ui-playground/site
          single-commit: true
          clean: true
          target-folder: playground