name: Deploy Playground And Sync to Gitee

on:
  push:
    branches: [main]

jobs:
  deploy-playground-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile && node scripts/bootstrap.mjs

      - name: Build playground
        run: pnpm build:play

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: playground-gh-page
          folder: packages/varlet-ui-playground/site
          single-commit: true
          clean: true

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:varletjs/varlet.git
          destination-repo: git@gitee.com:varlet/varlet-ui-playground.git
